# learner -service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learner-service
  template:
    metadata:
      labels:
        app: learner-service
    spec:
      containers:
      - name: learner-service
        image: rxshi01/learner-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET